/** Deliberate design-preview fixtures. Never used by Supabase queries or seller accounts. */
export type DemoProduct = {
  id: string;
  name: string;
  price: number;
  category: string;
  seller: string;
  image: string;
  city: string;
  stock: number;
};
export const demoProducts: DemoProduct[] = [
  {
    id: "kitenge-handbag",
    name: "Kitenge Handbag",
    price: 450,
    category: "Fashion",
    seller: "Chisomo Fashion",
    image: "/images/handbag.webp",
    city: "Lusaka",
    stock: 8,
  },
  {
    id: "white-sneakers",
    name: "Classic White Sneakers",
    price: 620,
    category: "Fashion",
    seller: "Urban Kicks",
    image: "/images/sneakers.webp",
    city: "Lusaka",
    stock: 12,
  },
  {
    id: "shea-body-butter",
    name: "Shea Body Butter",
    price: 280,
    category: "Beauty",
    seller: "Zambezi Naturals",
    image: "/images/skincare.webp",
    city: "Lusaka",
    stock: 15,
  },
  {
    id: "wireless-headphones",
    name: "Wireless Headphones",
    price: 950,
    category: "Electronics",
    seller: "TechHub Zambia",
    image: "/images/headphones.webp",
    city: "Kitwe",
    stock: 6,
  },
  {
    id: "rattan-table-lamp",
    name: "Rattan Table Lamp",
    price: 720,
    category: "Home",
    seller: "Home & Co",
    image: "/images/lamp.webp",
    city: "Lusaka",
    stock: 10,
  },
  {
    id: "zambian-coffee",
    name: "Zambian Coffee Beans",
    price: 150,
    category: "Food",
    seller: "Kala Coffee",
    image: "/images/coffee.webp",
    city: "Ndola",
    stock: 25,
  },
  {
    id: "woven-basket",
    name: "Handwoven Basket",
    price: 380,
    category: "Home",
    seller: "Kubwa Crafts",
    image: "/images/basket.webp",
    city: "Lusaka",
    stock: 4,
  },
  {
    id: "ankara-dress",
    name: "Ankara Wrap Dress",
    price: 520,
    category: "Fashion",
    seller: "Chisomo Fashion",
    image: "/images/seller-hero.webp",
    city: "Lusaka",
    stock: 5,
  },
  {
    id: "indoor-plant",
    name: "Indoor Plant",
    price: 350,
    category: "Home",
    seller: "Green Space",
    image: "/images/plant.webp",
    city: "Lusaka",
    stock: 9,
  },
  {
    id: "everyday-tote",
    name: "Everyday Woven Tote",
    price: 420,
    category: "Fashion",
    seller: "Chisomo Fashion",
    image: "/images/basket.webp",
    city: "Lusaka",
    stock: 7,
  },
  {
    id: "natural-face-cream",
    name: "Natural Face Cream",
    price: 260,
    category: "Beauty",
    seller: "Zambezi Naturals",
    image: "/images/skincare.webp",
    city: "Ndola",
    stock: 18,
  },
  {
    id: "coffee-gift-set",
    name: "Coffee Gift Set",
    price: 320,
    category: "Food",
    seller: "Kala Coffee",
    image: "/images/coffee.webp",
    city: "Kitwe",
    stock: 11,
  },
];
export const categories = [
  "All products",
  "Fashion",
  "Beauty",
  "Electronics",
  "Home",
  "Food",
  "Health",
  "Sports",
  "Other",
];
